/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Attendance: typeof import('./components/attendance.vue')['default']
    Calen: typeof import('./components/calen.vue')['default']
    Calendar: typeof import('./components/calendar.vue')['default']
    Chart: typeof import('./components/chart.vue')['default']
    Charttwo: typeof import('./components/charttwo.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Inform: typeof import('./components/inform.vue')['default']
    Noticeone: typeof import('./components/noticeone.vue')['default']
    Noticetwo: typeof import('./components/noticetwo.vue')['default']
    Roomuse: typeof import('./components/roomuse.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
